databases:
  - name: olimebackend
    databaseName: olimebackend
    user: olimebackend
    region: singapore

services:
  - type: web
    name: olimebackend
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: olimebackend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4